* _Пензенское региональное отделение Фонда социального страхования_

* Цель организации
  1) Обеспечение обязательного социального страхования граждан России;
  2) Управление средствами государственного социального страхования
     Российской Федерации.
  
* Отделение фонда социального страхования осуществляет:
  1) Выплату пособий по временной нетрудоспособности;
  2) Выплату пособий в связи с материнством и детством;
  3) Обеспечение социальными пособиями на погребение;
  4) Санаторно-курортное лечение. Оздоровление детей;
  5) Финансирование проведения углубленных медицинских осмотров
     работников занятых на работах с вредными и (или) опасными
     производственными факторами.

* Функции, которые могут быть автоматизированы с помощью информационной системы
** Организация банков данных по всем категориям страхователей (юр. и физ. лицах).
** Ежеквартальный приём и выверка отчётных данных страхователей ([[http://www.fss.ru/ru/fund/information_system/automation/2047.shtml][по форме 5 ФСС РФ]]).
** Хранение сведений о получателях страховых выплат.
** Ежеквартальный отчёт о своей деятельности центральному аппарату Фонда.
