_Пензенское региональное отделение Фонда социального страхования_

* Цель организации
  
  1) Обеспечение обязательного социального страхования граждан России;
  2) Управление средствами государственного социального страхования
     Российской Федерации.
  
* Отделение фонда социального страхования осуществляет:
  
  1) Выплату пособий по временной нетрудоспособности;
  2) Выплату пособий в связи с материнством и детством;
  3) Обеспечение социальными пособиями на погребение;
  4) Санаторно-курортное лечение. Оздоровление детей;
  5) Финансирование проведения углубленных медицинских осмотров
     работников занятых на работах с вредными и (или) опасными
     производственными факторами.

* Функции, которые могут быть автоматизированы с помощью информационной системы

** Организация банков данных по всем категориям страхователей (юр. и физ. лицах).

*** Идентификация входной информации
    Заявление на регистрацию в качестве страхователя может исходить от
    физического или юридического лица на бумажном носителе с курьером.

*** Обработка входной информации
    На основе заявления на регистрацию и документов, предаставленных
    физ. или юр. лицом, специалист Фонда (оператор) заносит информацию
    в базу данных страхователей. При этом страхователю присваивается
    регистрационный номер и код подчиненности; определяется филиал
    регионального отделения Фонда, который будет осуществлять
    взаимодействие со страхователем.

    В данном случае к информации получают доступ сам оператор,
    администраторы БД.

    Используемые программные приложения:
    - программа для ввода данных страхователя;
    - база данных HiTech;
    - ОС Windows.

*** Описание результата обработки
    После обработки данные о страхователу представлены в
    формализованном виде и хранятся в базе данных, доступ к которой
    (удаление, модификация) может осуществлять администратор баз
    данных с использованием СУБД HiTech.
    

** Ежеквартальный приём и выверка отчётных данных страхователей ([[http://www.fss.ru/ru/fund/information_system/automation/2047.shtml][по форме 5 ФСС РФ]]).

*** Идентификация входной информации.
    Информация исходит от страхователя (предприятия, фирмы,
    индивидуального предпринимателя).

    Отчётные данные поступают с курьером (представителем страхователя)
    на бумажном носитетеле или через интернет (страхователь после
    указания необходимых паролей может получить доступ через интернет к
    своей отчетной информации в базе данных Фонда и прямо там
    сформировать очередной ежеквартальных отчет). Отчёт исходит от
    бухгалтера страхователя к оператору ИС Фонда.

*** Обработка входной информации
    Если отчёт поступает с курьером на бумажном носителе, специалист
    Фонда (оператор) на своём рабочем месте осуществляет ручной ввод
    информации в базу данных (т.е. эти данные приводятся к
    формализованному виду), которая хранится на сервере баз
    данных. Если отчёт поступает через интернет, то он обрабатывается
    автоматически.

    В данном случае к информации получают доступ сам оператор,
    администраторы БД.

    Используемые программные приложения:
    - программа для ввода данных отчёта;
    - база данных HiTech;
    - ОС Windows.
      
    Отчётные данные страхователя заносятся в базу данных (приводятся к
    формализованному виду) специалистом фонда или автоматически.
    
*** Описание результата обработки
    После обработки отчётные данные страхователя представлены в
    формализованном виде и хранятся в базе данных, доступ к которой
    (удаление, модификация) может осуществлять администратор баз
    данных с использованием СУБД HiTech.
    

** Хранение сведений о получателях страховых выплат.
   
** Ежеквартальный отчёт о своей деятельности центральному аппарату Фонда.

* Разработка структуры ИС организации
  1) Серверная ферма:
     - почтовый сервер;
     - сервер БД;
     - сервер обработки, на котором установлена СУБД;
     - сервер резервного копирования.
  2) Автоматизированные рабочие места:
     - операторов;
     - администратора БД (резервного копирования);
     - администратора почтового сервера;
     - администратора ИБ;
     - администратора локальной сети.
